### PR TITLE
Fix Casting Basin Automation

### LINKED ISSUE #900: Using "mechanical user" on casting basin drops nothing
When I tried to use mechanical user from the extra utilities 2 to drop item from the casting basin, it basically voids the item. The casting basin still doesnt support an item outlet (not even immersive engineering´s extraction belt works!), and it doesnt even store the items, so when I try to get enough rails for a decent railway, I need to do that ultra-tedious job of grabbing it manually for at least an hour! 
Anyway, I use the newest 1.12.2 version (1.8.0), together with newest according version of TrackAPI, UMC and Immersive engineering.

### PR DESCRIPTION
**Pull request by Appw0**
While this does not completely fix #900, #763 or #738, it does resolve the underlying issue of the multiblock not being able to be automated. In my testing, this allows the port on the casting basin to be extracted from by a hopper, or other modded extraction device. While this doesn't fix the mechanical user problem, it does allow the basin to be simply automated with a hopper. I have successfully made a completely automated system for crafting rails in a singleplayer world with this change, and am quite happy with it.

### CODE REVIEW

**Comment by rendragnet** [comment]
Sorry to drag up an ooold issue, but I can't find documentation or examples for this new functionality, and my trial and error so far hasn't produced useful results.  Can someone explain (or show a picture of) exactly the hopper needs to be please? :)

I thought I could kinda figure it out based on the code, and where the power input was, but no go :(

Thankyou!

**Comment by km00700** [comment]
https://cdn.discordapp.com/attachments/355731184157720579/991144002852225084/2022-06-27_17.48.25.png

https://cdn.discordapp.com/attachments/355731184157720579/991144146515525712/2022-06-27_17.49.07.png
(note orientation of the power inputs: tall part of plate roller is on the back right side)

https://cdn.discordapp.com/attachments/355731184157720579/991144218229739610/2022-06-27_17.49.25.png

https://cdn.discordapp.com/attachments/355731184157720579/991143881196437504/2022-06-27_17.50.04.png

**Comment by rendragnet** [comment]
@km00700 Oh my lord, there's a port on the side 🤦‍♂️ I tried all around the main steel reservoir, and the end of the casting area, but hadn't checked the sides!  (My casting basin is recessed 2 blocks into the ground)  Thankyou! :)

**Comment by km00700** [comment]
you should also be able to pull out from the bottom of that block with the port too.

**Pull request merged**
