### PR TITLE
Added Cab Car Type Locomotive

### PR DESCRIPTION
**Pull request by km00700**

### CODE REVIEW

**Comment by cam72cam** [comment]
What's the difference between this and a diesel locomotive?

**Comment by km00700** [comment]
no limitation on fuel, and as a separate type may be able to have control offered in only a certain part of the stock.

**Comment by Kriegfox** [comment]
You understand a Cab car is by definition unpowered in most cases and controls a powered "locomotive" from the opposite end of the train?

**Comment by km00700** [comment]
I'm well aware.

**Comment by km00700** [comment]
Hence it doesn't require fuel, and will eventually only allow for a defined are to be controllable.

**Comment by km00700** [comment]
I called it cab car locomotive due to the in-code class inheritance

**Pull request closed without merging**
