### PR TITLE
New physics

### PR DESCRIPTION
**Pull request by CelestiaTheDryad**
See #505

### CODE REVIEW

**Comment by cam72cam** [comment]
I'll give this a try tonight.  If it is more accurate than what's currently in there (which it probably is) I'll merge it.  I know @Kriegfox is working on perfection, but that can be built on top of this work.

**Comment by JustDesoroxxx** [comment]
So what was the result of the trial?

**Comment by cam72cam** [comment]
The underlying coupling/netcode/"physics" is currently all tied together in a bad way.  My next project after the render overhaul is to refactor that (late spring / summer project).  My goal is to clean up the code so other folks can add/modify physics without worrying about the crazy set of interdependent pieces.

This stuff grew organically over a few years and I'm putting in the work to reign it in / fix it up so other folks can more easily contribute to it.

**Comment by Desoroxxx** [comment]
Why did this close as it been implemented?

**Pull request closed without merging**
